project_id = "uuioedhcwydmtoywytq"

[functions.seed-admin]
verify_jwt = false

[functions.quotes-create]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.quote-claim]
verify_jwt = true

[functions.health-email]
verify_jwt = false

[functions.tracking-get]
verify_jwt = false

[functions.inbox-create]
verify_jwt = false


