name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          echo "Deploying Supabase functions..."
          
          # Link to project
          supabase link --project-ref $SUPABASE_PROJECT_REF
          
          # Deploy all functions
          supabase functions deploy send-quote-email
          supabase functions deploy resend-quote-email  
          supabase functions deploy resend-confirmation-email
          supabase functions deploy quotes-create
          supabase functions deploy send-confirmation-email
          supabase functions deploy test-email
          supabase functions deploy tracking-get
          supabase functions deploy inbox-create
          supabase functions deploy execute-event
          supabase functions deploy seed-admin
          supabase functions deploy seed-demo
          
          echo "✅ All functions deployed successfully!"